# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "007"
# PUSHER_KEY: ABC123
# PUSHER_SECRET: ABC123
# STRIPE_API_KEY: ABC123
# STRIPE_PUBLIC_KEY: ABC123

# See https://github.com/laserlemon/figaro for information on how this works

S3_REGION: S3_REGION_STAGING
S3_KEY: S3_KEY_STAGING
S3_SECRET: S3_SECRET_STAGING
S3_BUCKET: S3_BUCKET_STAGING
FACEBOOK_APP_ID: FACEBOOK_APP_ID_STAGING
FACEBOOK_SECRET: FACEBOOK_SECRET_STAGING
FACEBOOK_USER_ID: FACEBOOK_USER_ID_STAGING
PAYPAL_URL_PREFIX: PAYPAL_URL_PREFIX_STAGING
PAYPAL_EMAIL_ADDRESS: PAYPAL_EMAIL_ADDRESS_STAGING
PAYPAL_API_USERNAME: PAYPAL_API_USERNAME_STAGING
PAYPAL_API_PASSWORD: PAYPAL_API_PASSWORD_STAGING
PAYPAL_API_SIGNATURE: PAYPAL_API_SIGNATURE_STAGING
PAYPAL_CERT_ID: PAYPAL_CERT_ID_STAGING
