# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# See https://github.com/laserlemon/figaro for information on how this works

S3_REGION: S3_REGION_STAGING
S3_KEY: S3_KEY_STAGING
S3_SECRET: S3_SECRET_STAGING
S3_BUCKET: S3_BUCKET_STAGING
FACEBOOK_APP_ID: FACEBOOK_APP_ID_STAGING
FACEBOOK_SECRET: FACEBOOK_SECRET_STAGING
FACEBOOK_USER_ID: FACEBOOK_USER_ID_STAGING
PAYPAL_URL_PREFIX: PAYPAL_URL_PREFIX_STAGING
PAYPAL_EMAIL_ADDRESS: PAYPAL_EMAIL_ADDRESS_STAGING
PAYPAL_API_USERNAME: PAYPAL_API_USERNAME_STAGING
PAYPAL_API_PASSWORD: PAYPAL_API_PASSWORD_STAGING
PAYPAL_API_SIGNATURE: PAYPAL_API_SIGNATURE_STAGING
PAYPAL_CERT_ID: PAYPAL_CERT_ID_STAGING
