source "https://rubygems.org"

#ruby "1.9.3"

gem "rails", "3.2.14"
gem "pg"
gem "unicorn"

group :development do
  gem "heroku"
  gem "heroku_san"
  gem "debugger"
end

group :assets do
  gem "sass-rails",   "~> 3.2.3"
  gem "coffee-rails", "~> 3.2.1"
  gem "uglifier", ">= 1.0.3"
  gem 'jquery-fileupload-rails', '0.4.0'
end

gem "jquery-rails"

gem 'tinymce-rails', '3.4.9'

gem "acts_as_rateable", :git => "git://github.com/jimlambie/acts_as_rateable.git", :branch => "master"
gem "addresslogic", :git => "git://github.com/nathansamson/addresslogic.git"
gem 'exception_notification', :git => "git://github.com/smartinez87/exception_notification.git", :tag => "v3.0.1"
gem "niche_providers", :git => "git://github.com/jimlambie/niche-providers-engine", :branch => 'master'
